name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci
      - run: npm run build

      - run: |
          TAG="${GITHUB_REF_NAME#v}"
          FILE_VER=$(jq -r .version manifest.json)
          [ "$TAG" = "$FILE_VER" ] || exit 1
          mkdir -p mosaic
          cp manifest.json main.js styles.css mosaic/ 2>/dev/null || true
          zip -r "mosaic-${TAG}.zip" mosaic

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            mosaic-*.zip
          token: ${{ github.token }}
